package com.testforge.backend.ai.provider;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.testforge.backend.ai.dto.AgentType;
import com.testforge.backend.ai.dto.AiPrompt;
import com.testforge.backend.ai.dto.AiResult;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Deterministic offline stand-in for a real LLM provider. Used automatically
 * when no Gemini API key is configured (app.ai.provider=mock, the default),
 * so the whole pipeline — upload, analyze, generate tests, score risk, build
 * a PDF report — can be demoed end-to-end without any external API access.
 * It still reflects real project data (endpoint names/paths parsed out of the
 * prompt) so the output looks tailored rather than static boilerplate.
 */
public class MockAiProvider implements AiProvider {

    private static final Pattern ENDPOINT_LINE = Pattern.compile("-\\s+([A-Z]+)\\s+(\\S+)");

    private final ObjectMapper objectMapper;

    public MockAiProvider(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    @Override
    public AiResult generate(AiPrompt prompt) {
        long start = System.currentTimeMillis();
        try {
            List<String[]> endpoints = extractEndpoints(prompt.userContent());
            Object payload = switch (prompt.agentType()) {
                case CODE_SUMMARY -> codeSummary(endpoints);
                case TEST_GENERATION -> testGeneration(endpoints);
                case SECURITY_ANALYSIS -> securityAnalysis(endpoints);
                case RISK_SCORE -> riskScore(endpoints);
            };
            String json = objectMapper.writeValueAsString(payload);
            return new AiResult(getName(), json, System.currentTimeMillis() - start, true, null);
        } catch (Exception ex) {
            return new AiResult(getName(), null, System.currentTimeMillis() - start, false, ex.getMessage());
        }
    }

    private List<String[]> extractEndpoints(String userContent) {
        List<String[]> result = new ArrayList<>();
        Matcher m = ENDPOINT_LINE.matcher(userContent);
        while (m.find() && result.size() < 8) {
            result.add(new String[]{m.group(1), m.group(2)});
        }
        return result;
    }

    private Map<String, Object> codeSummary(List<String[]> endpoints) {
        String epList = endpoints.isEmpty() ? "no clearly identifiable HTTP endpoints"
                : endpoints.size() + " HTTP endpoint(s) including " + endpoints.get(0)[0] + " " + endpoints.get(0)[1];
        return Map.of(
                "summary", "This project appears to be a service exposing " + epList
                        + ". (Generated by the offline mock AI provider — configure app.ai.provider=gemini and a "
                        + "GEMINI_API_KEY to get real model-generated analysis.)",
                "keyResponsibilities", List.of(
                        "Handles incoming HTTP requests for its exposed endpoints",
                        "Applies business logic and persists/retrieves data",
                        "Returns structured responses to callers"
                ),
                "notableObservations", List.of(
                        "Mock provider active — no external AI call was made",
                        "Attach a Swagger/OpenAPI spec for more precise endpoint-level analysis"
                )
        );
    }

    private Map<String, Object> testGeneration(List<String[]> endpoints) {
        List<Map<String, Object>> tests = new ArrayList<>();
        tests.add(Map.of(
                "type", "UNIT",
                "title", "shouldReturnExpectedResultForValidInput",
                "targetName", "core business method",
                "framework", "JUnit5",
                "description", "Happy-path unit test for a representative business method.",
                "code", "@Test\nvoid shouldReturnExpectedResultForValidInput() {\n    // Arrange\n    var input = validSampleInput();\n    // Act\n    var result = serviceUnderTest.process(input);\n    // Assert\n    assertThat(result).isNotNull();\n}"
        ));

        if (endpoints.isEmpty()) {
            tests.add(genericApiTest("UNKNOWN", "/api/example"));
        } else {
            for (String[] ep : endpoints) {
                tests.add(genericApiTest(ep[0], ep[1]));
            }
        }

        tests.add(Map.of(
                "type", "EDGE_CASE",
                "title", "shouldRejectNullAndEmptyPayloads",
                "targetName", endpoints.isEmpty() ? "request handler" : endpoints.get(0)[1],
                "framework", "JUnit5",
                "description", "Edge-case coverage for null/empty/huge/unicode input.",
                "code", "@ParameterizedTest\n@NullAndEmptySource\nvoid shouldRejectNullAndEmptyPayloads(String input) {\n    assertThatThrownBy(() -> serviceUnderTest.process(input))\n        .isInstanceOf(IllegalArgumentException.class);\n}"
        ));

        tests.add(Map.of(
                "type", "SECURITY",
                "title", "shouldRejectSqlInjectionAttempt",
                "targetName", endpoints.isEmpty() ? "request handler" : endpoints.get(0)[1],
                "framework", "JUnit5",
                "description", "Confirms user-supplied input is parameterized/escaped, not concatenated into queries.",
                "code", "@Test\nvoid shouldRejectSqlInjectionAttempt() {\n    String malicious = \"' OR '1'='1\";\n    var response = restTemplate.postForEntity(endpoint, new Request(malicious), ErrorResponse.class);\n    assertThat(response.getStatusCode().is4xxClientError()).isTrue();\n}"
        ));

        return Map.of("tests", tests);
    }

    private Map<String, Object> genericApiTest(String method, String path) {
        return Map.of(
                "type", "API",
                "title", "shouldHandle" + method + capitalizePath(path),
                "targetName", method + " " + path,
                "framework", "RestAssured",
                "description", "Positive-path API test for " + method + " " + path + ", plus paired negative case.",
                "code", "@Test\nvoid shouldHandle" + method + capitalizePath(path) + "() {\n    given()\n        .contentType(ContentType.JSON)\n        .when()\n        ." + method.toLowerCase() + "(\"" + path + "\")\n        .then()\n        .statusCode(anyOf(is(200), is(201)));\n}"
        );
    }

    private String capitalizePath(String path) {
        String cleaned = path.replaceAll("[^a-zA-Z0-9]", " ").trim();
        StringBuilder sb = new StringBuilder();
        for (String part : cleaned.split("\\s+")) {
            if (!part.isEmpty()) {
                sb.append(Character.toUpperCase(part.charAt(0))).append(part.substring(1));
            }
        }
        return sb.isEmpty() ? "Endpoint" : sb.toString();
    }

    private Map<String, Object> securityAnalysis(List<String[]> endpoints) {
        List<Map<String, Object>> findings = new ArrayList<>();
        findings.add(Map.of(
                "category", "BROKEN_AUTH",
                "severity", "MEDIUM",
                "description", "Could not confirm rate limiting or account lockout on authentication endpoints from static context alone.",
                "recommendation", "Add rate limiting and lockout after repeated failed login attempts.",
                "location", endpoints.isEmpty() ? "authentication endpoint" : endpoints.get(0)[1]
        ));
        findings.add(Map.of(
                "category", "SENSITIVE_DATA_EXPOSURE",
                "severity", "LOW",
                "description", "Verify error responses do not leak stack traces or internal identifiers to clients.",
                "recommendation", "Return generic error messages in production; log details server-side only.",
                "location", "global exception handling"
        ));
        findings.add(Map.of(
                "category", "SQL_INJECTION",
                "severity", "MEDIUM",
                "description", "Confirm all database access uses parameterized queries / an ORM rather than string concatenation.",
                "recommendation", "Use JPA/parameterized queries everywhere; add a SAST rule to catch string-built SQL.",
                "location", "data access layer"
        ));
        return Map.of("findings", findings);
    }

    private Map<String, Object> riskScore(List<String[]> endpoints) {
        int score = Math.min(85, 30 + endpoints.size() * 5);
        return Map.of(
                "score", score,
                "reasons", List.of(
                        "Score generated by offline mock provider based on endpoint count and generic heuristics",
                        endpoints.isEmpty() ? "No endpoints detected to weigh risk against" : endpoints.size() + " endpoint(s) discovered, increasing exposed surface area"
                ),
                "coverageEstimatePercent", 40,
                "coverageGaps", List.of(
                        "Authentication/authorization edge cases",
                        "Negative and boundary-value API tests",
                        "Concurrency/race-condition scenarios"
                )
        );
    }

    @Override
    public String getName() {
        return "mock";
    }
}
